name: Auto PR to release branches
on:
  pull_request:
    branches: [main]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'

    strategy:
      matrix:
        branches: [release/2.6.0.0]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${GITHUB_HEAD_REF}
        destination_branch: ${{ matrix.BRANCHES }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
