name: Cherry pick to release branches
on:
  push:
    branches:
    - dependabot/docker/**

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'

    strategy:
      matrix:
        branches: [release/2.6.0.0]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        pesist-credentials: false
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ matrix.BRANCHES }}
        github_token: ${{ secrets.CHERRY_PICK_TOKEN }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}