name: Cherry pick to release branches
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  backport-pr:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branches: [release/2.6.0.0]

    steps:
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
        pesist-credentials: true
    - name: Backport PR by cherry-pick-ing
      uses: Nathanmalnoury/gh-backport-action@master
      with:
        pr_branch: ${{ matrix.BRANCHES }}
        github_token: ${{ secrets.CHERRY_PICK_TOKEN }}
