name: Cherry pick to release branches
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    
    strategy:
      matrix:
        branches: [release/2.6.0.0]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cherry pick to ${{ matrix.BRANCHES }}
      uses: Nathanmalnoury/gh-backport-action@master
      with:
        pr_branch: ${{ matrix.BRANCHES }}
        github_token: ${{ secrets.CHERRY_PICK_TOKEN }}