on:
  push:
    branches:
      - main

name: Create Github Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch 
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: steps['versioning']['outputs']['RETURN_STATUS'] == '0'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.versioning.outputs.version }}
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: hutchic/github-actions # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
          tag-custom: ${{ steps.versioning.outputs.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest
      - name: Update values.yaml
        run: yq w -i values.yaml image.tag ${{ steps.versioning.outputs.version }}
      - name: Commit back
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Release ${{ steps.versioning.outputs.version }}
          branch: main
