on:
  push:
    branches:
      - main

name: Create Github and Docker Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Release
        id: release
        uses: ahmadnassri/action-semantic-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        if: steps['release']['outputs']['published'] == 'true'
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: hutchic/github-actions
          tags: |
            type=semver,pattern={{version}},value=${{ steps.release.outputs.release-version }}
            type=ref,event=branch
            type=sha
      - name: Set up QEMU
        if: steps['release']['outputs']['published'] == 'true'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: steps['release']['outputs']['published'] == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: steps['release']['outputs']['published'] == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps['release']['outputs']['published'] == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
